graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Deployment View: Interview Recorder - Production"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 72 ["User's Computer"]
      style 72 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 75 ["Audio Hardware"]
        style 75 fill:#ffffff,stroke:#444444,color:#444444

        76["<div style='font-weight: bold'>Microphone</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: Audio hardware]</div><div style='font-size: 80%; margin-top:10px'>Audio input device</div>"]
        style 76 fill:#666666,stroke:#474747,color:#ffffff
        77["<div style='font-weight: bold'>Speakers / Headphones</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: Audio hardware]</div><div style='font-size: 80%; margin-top:10px'>Audio output device</div>"]
        style 77 fill:#666666,stroke:#474747,color:#ffffff
      end

      subgraph 78 ["Local Storage"]
        style 78 fill:#ffffff,stroke:#444444,color:#444444

        79[("<div style='font-weight: bold'>My Documents</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: NTFS]</div><div style='font-size: 80%; margin-top:10px'>User's Documents folder<br />(InterviewRecordings)</div>")]
        style 79 fill:#85bbf0,stroke:#5d82a8,color:#000000
      end

    end

  end