graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Deployment View: Interview Recorder - Production"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 70 ["User's Computer"]
      style 70 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 73 ["Audio Hardware"]
        style 73 fill:#ffffff,stroke:#444444,color:#444444

        74["<div style='font-weight: bold'>Microphone</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: Audio hardware]</div><div style='font-size: 80%; margin-top:10px'>Audio input device</div>"]
        style 74 fill:#666666,stroke:#474747,color:#ffffff
        75["<div style='font-weight: bold'>Speakers / Headphones</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: Audio hardware]</div><div style='font-size: 80%; margin-top:10px'>Audio output device</div>"]
        style 75 fill:#666666,stroke:#474747,color:#ffffff
      end

      subgraph 76 ["Local Storage"]
        style 76 fill:#ffffff,stroke:#444444,color:#444444

        77[("<div style='font-weight: bold'>My Documents</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: NTFS]</div><div style='font-size: 80%; margin-top:10px'>User's Documents folder<br />(InterviewRecordings)</div>")]
        style 77 fill:#85bbf0,stroke:#5d82a8,color:#000000
      end

    end

  end